
name: Xcode - Build and Analyze

on:
  workflow_dispatch:
    inputs:
       version:
          description: 'version'     
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - run: |
          echo $(git tag -l)


      - name: Check if version exists
        id: check_version
        run: |
          echo "${{ github.event.inputs.version }}"
          echo $(git tag)
          existing_tag=$(git tag --list "${{ github.event.inputs.version }}")
          #echo "tag $existing_tag"
          echo "tag ${existing_tag//$'\n'/}"

          
          if [[ -z "$existing_tag" ]]; then
            echo "::set-output name=version_exists::false"
          else
            echo "::set-output name=version_exists::true"
          fi
        continue-on-error: true

      - name: version eixst
        if: steps.check_version.outputs.version_exists == 'false'
        run: |
            echo "value is false"
            echo "$steps.check_version.outputs.version_exists"
            
      - name: Delete existing version
        if: steps.check_version.outputs.version_exists == 'true'
        run: |
          existing_tag="${{ github.event.inputs.version }}"
          echo "$existing_tag"

          #release_id=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/tags/$existing_tag" | jq -r '.id')
          release_id=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: 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"  -H  "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/sujin4525/loplat-ios-spm-test/releases/tags/$existing_tag | jq -r '.id')

          echo "Release ID: $release_id"
          #curl -L -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/sujin4525/loplat-ios-spm-test/releases/$release_id
          curl -L -X DELETE -H "Authorization: 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" https://api.github.com/repos/sujin4525/loplat-ios-spm-test/releases/$release_id




      - name: Delete existing tag
        if: steps.check_version.outputs.version_exists == 'true'
        run: |
          existing_tag="${{ github.event.inputs.version }}"
          echo "$existing_tag"
          
          git fetch
          git pull

          git tag -d $existing_tag
          #git push origin :refs/tags/$existing_tag
          git push --delete origin $existing_tag
          echo "Deleted existing tag: $existing_tag"

      - name: Release 생성
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.event.inputs.version }} 
          release_name: ${{ github.event.inputs.version }} 
          draft: false
          prerelease: false
          
     

