name: Xcode - Build and Analyze

on:
  workflow_dispatch:
    inputs:
       version:
          description: 'version'     
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check for existing tag
        run: |
          existing_tag=$(git ls-remote --tags "https://github.com/$GITHUB_REPOSITORY.git" "refs/tags/$VERSION")
          if [[ -n "$existing_tag" ]]; then
            echo "Tag $VERSION already exists. Deleting tag and release..."
            release_id=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/tags/$existing_tag" | jq -r '.id')
            echo "Release ID: $release_id"

            curl -L -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id
            #curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$VERSION"
            #git push origin --delete "$VERSION"
          fi


